### ISSUE TITLE
repo-mountie commits do not contain DCO sign-off

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/repomountie#101]
The commits created by `repo-mountie` do not contain DCO Sign-Off in the commit message.  This is causing issues for the DTS team as many of our repositories are being contributed to [Hyperledger](https://github.com/hyperledger).  Linux Foundation projects require DCO sign-off on all commits.   If `repo-mountie` commits get merged into these repositories we must amend the commit messages which rebases and end up re-writing the commit history.

Example DCO sign-off:
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>

**Comment by jleach** [comment]
@WadeBarnes For this to work, does the bot just need to add `Signed-off-by: repomountie <bla@gov.bc.ca>` or does it require anything more advanced like GPG/PGP signing? If the former its no problem to add.

**Comment by WadeBarnes** [comment]
Just `Signed-off-by: repomountie <bla@gov.bc.ca>`
