### ISSUE TITLE
The bot should not mark issues stale if they have the "neverstale" lable.

### ISSUE THREAD

**Issue by jleach** [bcgov/repomountie#110]
The bot has a feature where, if configured, it will mark issues as stale after N days. This is great but some issues should never get stale. It would be great if the bot would ignore issues that are marked with a specific labels. For example, if an issue has the label "neverstale" it should not mark it as stale.

**Comment by AndrewJun97** [comment]
This change has been implemented Oct.2.2020 on Pathfinder3.11
