### ISSUE TITLE
repomountie not finding existing project lifecycle badge

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/repomountie#123]
**Describe the issue**
{repomountie} opened a number of issues to add a lifecycle badge where they already exist in the `README` e.g. https://github.com/bcgov/safepaths/issues/5

**Additional context**
I wonder if the scan is failing in situations where the badge code is adjacent to code for another badge (e.g. Apache 2.0 badge)?

**Definition of done**
{repomountie} should only open an issue to add a lifecycle badge if one does not exists in the `README`

**Comment by stephhazlitt** [comment]
OK, so the bot also does not detect the `lifecycle badge` even with the one badge, here is an [example](https://github.com/bcgov/bcgov-data-science-cop/issues?q=is%3Aissue+is%3Aclosed), which I guess explains the double notice (i.e. two issues)?

**Comment by AndrewJun97** [comment]
Seems like the bot is creating issues regardless of an existing badge. Did those issues exist concurrently, or did repomountie create a new issue after you closed one?

**Comment by stephhazlitt** [comment]
I think I closed #11 before #12 was opened  --- in the hope the bot would not assign me to it and add clutter into my notices. However, even the first issue should not have happened as this repo had the appropriate lifecycle badge.

**Comment by TylerMuhly** [comment]
This happening to us too; please stop.

**Comment by danagerous** [comment]
I've received 3 notifications since yesterday even though I added the lifecycle badge to my repos on the first notice. The mountie is going rogue.

**Comment by patricksimonian** [comment]
nothing worse than a rogue bot. We are hoping it hasn't joined the rebel alliance. For now its been scaled down to 0 pods. Sorry for the inconvenience

**Comment by AndrewJun97** [comment]
Closing. PR is tracked in https://github.com/bcgov/repomountie/pull/127

We're looking to re-deploy this feature once issue https://github.com/bcgov/repomountie/issues/124 is resolved.
