### ISSUE TITLE
Robot asks for updates on closed issues.

### ISSUE THREAD

**Issue by jleach** [bcgov/repomountie#132]
## Description

The robot appears to be asking for updates on life-cycle badge issues even though the issue is closed.

See [this](https://github.com/bcgov/devops-credential-issuer/issues/28) example.

## Expected Results

When an issue is closed, the bot should no longer request updates for that issue.

**Comment by jleach** [comment]
@yhfreeman You might be interested in this issue to get more involved with the robot. I've also included @AndrewJun97 who wrote the feature. Its probably worth fixing this issue because we have so many repos the blast radius of this issue could be wide.

**Comment by AndrewJun97** [comment]
@jleach Hey Jason, is this a bug? It looks like that issue wasn't closed until 2 days ago. If it was an open issue it would make sense that repomountie gave it a reminder.

**Comment by jleach** [comment]
That's a good point. I've Cced you in RC with the person who reported the issue..
