### ISSUE TITLE
Project Lifecycle Badge False Positives

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/repomountie#135]
**Describe the issue**
Multiple repos have been receiving multiple issues to create lifecycle badges even though they already exist.

**Additional context**
These repos use badge styling and reference-style links.

**Definition of done**
Stop creating issues for repos that already have lifecycle badges.  Limit those to one per repo.

Duplicated issues:
https://github.com/bcgov/containerization-and-cloud-economic-model/issues/21
https://github.com/bcgov/containerization-and-cloud-economic-model/issues/20
https://github.com/bcgov/containerization-and-cloud-economic-model/issues/19
https://github.com/bcgov/containerization-and-cloud-economic-model/issues/17
https://github.com/bcgov/site-status-checker/issues/11
https://github.com/bcgov/site-status-checker/issues/10
https://github.com/bcgov/site-status-checker/issues/9
https://github.com/bcgov/site-status-checker/issues/8
https://github.com/bcgov/site-status-checker/issues/6
https://github.com/bcgov/wps/issues/984
https://github.com/bcgov/wps/issues/970
https://github.com/bcgov/wps/issues/969
https://github.com/bcgov/wps/issues/961
https://github.com/bcgov/wps/issues/636

UPDATE - PR created: https://github.com/bcgov/repomountie/pull/137

**Comment by DerekRoberts** [comment]
PR https://github.com/bcgov/repomountie/pull/137

**Comment by jleach** [comment]
@patricksimonian @DerekRoberts Scaling up the bot. Let's keep an eye on this one.

**Comment by DerekRoberts** [comment]
@jleach @patricksimonian More false positives, but only on one of three repos.  It looks like reference-style links aren't supported.

https://github.com/bcgov/containerization-and-cloud-economic-model/issues/22

Reference-style link:
```
[![Lifecycle][lifecycle-shield]](https://github.com/bcgov/repomountie/blob/master/doc/lifecycle-badges.md)
[lifecycle-shield]: https://img.shields.io/badge/Lifecycle-Stable-97ca00?style=for-the-badge
```

**Comment by DerekRoberts** [comment]
Reference-style links removed after latest false positive.  Path of least resistance.

https://github.com/bcgov/containerization-and-cloud-economic-model/issues/26
https://github.com/bcgov/containerization-and-cloud-economic-model/pull/27
