### ISSUE TITLE
The bot is creating duplicate issues for dormant repositories

### ISSUE THREAD

**Issue by jleach** [bcgov/repomountie#149]
**Describe the issue**

When the bot reviews existing repositories for ones that are "dormant" it should not create an issue if one already exists. Right now, it's creating duplicate.

**Additional context**

https://github.com/bcgov/env-moosetracker-ios/issues

<img width="1288" alt="Screen Shot 2021-05-12 at 8 34 14 AM" src="https://user-images.githubusercontent.com/390891/118003067-13960180-b2fd-11eb-99f1-c1e70b356dba.png">

**Definition of done**

- [ ] If a repo already has an issue (closed or open) then it should not create any additional issues on the same subject.

**Comment by jleach** [comment]
@junminahn @wenzowski FYI. See how similar features use the search API to ensure that an issue does not exist before proceeding.

For improved testing @junminahn you can run the bot agains your own organization (local run it on your Mac).

**Comment by jleach** [comment]
@junminahn @wenzowski PS. I should have caught this in code review so this one is on me, but please, do more thorough testing going forward. I'll put more care into code reviews.

**Comment by junminahn** [comment]
@jleach yes, I see the duplicates for the same issue. I will add that logic to check existing ones before creating a new one.

**Comment by jleach** [comment]
@junminahn Ty. Please add tests for: Issue does not exists; issue exists and is open; issue exists and is closed. I think similar tests exists if not these will lead the way for a testing-best-practices-going-fwd. It most of my tests I have examples on how to check if different API is called etc. LMK if you want a walk through.

**Comment by junminahn** [comment]
@jleach I add a pr including the test coverages for the fix. please take a look. thanks!
https://github.com/bcgov/repomountie/pull/150

**Comment by stephhazlitt** [comment]
@jleach Any chance we down tools this feature while the team is debugging the duplications? My inboxes are getting (re)filled daily.

**Comment by jleach** [comment]
@stephhazlitt It is down ATM.
