### ISSUE TITLE
Bot is opening a new record for dormant repo the day after an issue was closed. 

### ISSUE THREAD

**Issue by gjlawran** [bcgov/repomountie#152]
**Describe the issue**
@jleach the repo-mountie bot opened a dormant issue https://github.com/bcgov/ligo-lib/issues/35 May 14th - two days after the same issue it raised was closed - https://github.com/bcgov/ligo-lib/issues/33 .

The bot is also creating duplicate open issues - https://github.com/bcgov/ligo-lib/issues/34 opened May 13 is the same issue https://github.com/bcgov/ligo-lib/issues/35 ,

Would  recommend and appreciate  the bot be rewritten so that all dormant issues it has been opened should now be closed, pending further review of the requirement for raising these issues and implementation testing being completed.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**

**Comment by jleach** [comment]
Thanks for reporting. I've since sales the bot down and we have #149 open to fix this. Will be done shortly.
