### ISSUE TITLE
Decomission project state badges

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/repomountie#5]
Love this, thank you! A future enhancement might inlclude checking for and, if absent, pinging/suggesting a [BCDevExchange  (or similar) project state badge](https://github.com/BCDevExchange/assets/blob/master/README.md) in repo README.md files?

> EDIT

## Tasks
- identify the appropriate lifecycle definitions for an application
- find an easy way for users to implement the project state badges based on above definitions
- use the repo mountie as an enforcer to implement the state badges

## Definition of Done

- functionality is added to repo mount to create issues on user repos when they are missing project state badges
- document summarizing lifecycle badges
- unit tests completed for functionality

**Comment by jleach** [comment]
Thanks for the feedback. Will look into it. We're also looking into any value in checking for 'topics' on a repo; essentially tags one can add to a repo to give context like: javascript, environment, statistics.

**Comment by stephhazlitt** [comment]
Is there a plan to decommission the BCDevExchange badges? I had opened this issue with the suggestion of adding functionality to the repo-mountie to _encourage_ folks to use them 🤞.

**Comment by stephhazlitt** [comment]
@mark-a-wilson Can we re-open this issue, since project state badges were not decommissioned or added to the bot, and now are not working. 'cc @jleach

**Comment by mark-a-wilson** [comment]
# Feature Request

### User stories

As **someone browsing bcgov GitHub repositories**, I would like a way, by quickly glancing at the repo's README, to get a sense what state the project is in, so that I can more quickly decide whether the repository is worth my time to explore further. 

As an **owner of a bcgov GitHub repository**, I would like to be notified that I need to add a project state badge to my README if I have forgotten to do so.

As **someone responsible for the quality/completeness of bcgov GitHub repos**, I would like for the process of ensuring that all repos have a project state badge, and that the owners of those that do not are notified, to be automated so that I don't have check this and send notifications manually.

### Discussion

* Original badges for project state were started in the early days in [BCDevExchange/assets](https://github.com/BCDevExchange/assets) 
* 'BCDevExchange' branding on the label doesn't seem to make sense anymore if this were to be a requirement for bcgov repos
* Here's a potential nomenclature for badges we could adopt: [https://www.tidyverse.org/lifecycle/](https://www.tidyverse.org/lifecycle/)
* We'd want the badges to have a stable URL so that badges in READMEs never become broken

**Comment by stephhazlitt** [comment]
@mark-a-wilson What are the next steps to move this proposed discussion along?

**Comment by mark-a-wilson** [comment]
@jleach - what is the likelihood that the job of creating a bot that would check for, and send reminders to bcgov repo owners about, the existence of a badge inside the README could make it onto your/your team's Sprint Backlog?

@stephhazlitt - I'd be happy to make new badges, but I suppose that unless it's someone's job to enforce/nag everyone to use them, it might not be worthwhile.

**Comment by stephhazlitt** [comment]
@jleach Many of the data science repos in bcgov GitHub are using the BCDevExchange ones (currently not working due to expired web certificate) , e.g. https://github.com/bcgov/bcdata

@mark-a-wilson Agreed. If these are not useful to the broader community then those of us that want them can use badge options from another organization. I would like to begin the manual work to remove the defunct ones if that is the likely path we will land on.

**Comment by mark-a-wilson** [comment]
^ Thanks for answering, Stephanie.

**Comment by patricksimonian** [comment]
Does it help it 

> @jleach - what is the likelihood that the job of creating a bot that would check for, and send reminders to bcgov repo owners about, the existence of a badge inside the README could make it onto your/your team's Sprint Backlog?
> 
> @stephhazlitt - I'd be happy to make new badges, but I suppose that unless it's someone's job to enforce/nag everyone to use them, it might not be worthwhile.

we could definitely configure the repo mountie to enforce and nag usage of project badges

**Comment by patricksimonian** [comment]
as far as a stable site for badges. I've seen this one in use for at least 5 years https://shields.io/

**Comment by patricksimonian** [comment]
![stable badge](https://img.shields.io/badge/status-stable-%23387230)

**Comment by patricksimonian** [comment]
hows that look ?

**Comment by stephhazlitt** [comment]
@patricksimonian These look great!

Would you see the community coalescing around a few life cycle ones (as with the BCDevExchange ones, or something similar but maybe iterated now that the org is more mature), or users can make their own?

**Comment by patricksimonian** [comment]
I think having the repomountie form opinions on the nomenclature should be good enough. That plus the colouring. From the org perspective it looks more consistent.  I'm not familiar with the BCDevExchange ones and it appears I can't see what they look like any longer !

**Comment by stephhazlitt** [comment]
The BCDevEchange labels were, in case that helps:

• inspiration
• experimentation
• dormant
• delivery
• retired

https://github.com/BCDevExchange/assets/blob/master/README.md

**Comment by patricksimonian** [comment]
so what is the label attached to that value? `status: inspiration` to me seems un-concrete

**Comment by stephhazlitt** [comment]
The label was BCDevExchange, I dug up this from a screen shot in a talk:
<img width="408" alt="Screen Shot 2020-09-21 at 4 26 50 PM" src="https://user-images.githubusercontent.com/7143861/93831347-6f553280-fc27-11ea-8e37-ae808f8e0f0f.png">

So more of an org label -- an updated version might be 'bcgov'? My vote would be for 'lifecycle' or something similar.

**Comment by stephhazlitt** [comment]
https://github.com/canada-ca/devex-pages

**Comment by stephhazlitt** [comment]
@patricksimonian  I think using your suggested img.shields.io approach is 👍 . 

Do you think a web page with suggested nomenclature and colours for bcgov GitHub is necessary (a url for the badges)? It could live in the BC-Policy-Framework-for-GitHub, or a stand-alone own repo, or in repo-mountie? 

I am happy to make a start if that is helpful.  'cc @mark-a-wilson

**Comment by patricksimonian** [comment]
I love the idea of having it the BC-Policy-Framework-for-GitHub. We can store a metadata file in the repo mountie for implementation purposes.

Lastly, wherever the content lives I'll make sure to pull it into the Devhub

**Comment by AndrewJun97** [comment]
Hi @stephhazlitt and @mark-a-wilson , in order to implement this enhancement I'll need URLs for all project state badges. Could you provide them please?

**Comment by patricksimonian** [comment]
@AndrewJun97 for clarity what urls are you talking about? Shields.io links?

**Comment by AndrewJun97** [comment]
> @AndrewJun97 for clarity what urls are you talking about? Shields.io links?

Yes, shields.io links would be great. Here is an example: https://img.shields.io/badge/lifecycle-experimental-orange

**Comment by patricksimonian** [comment]
Then is it far to say what you are asking for are what are the colours and lifecycle stages that we want to rollout in our first go at this?

**Comment by AndrewJun97** [comment]
Since the URL is defined by the colour and lifecycle stage, a list of colours and lifecycle stages is exactly what I'm looking for. 

Either a list of colours and lifecycle stages or URLs for the badges would be great!

**Comment by stephhazlitt** [comment]
The original set of bcdevexchange stages and colours, if useful, are here: https://github.com/BCDevExchange/assets/tree/master/images/badges

• delivery::green
• exploration::teal
• inspiration::blue
• dormant::orange
• retired::orange

**Comment by AndrewJun97** [comment]
Thanks for that Stephanie! 

Using the lifecycle label, the original badges would look like:
![Inspiration](https://img.shields.io/badge/Lifecycle-Inspiration-007EC6)
![Exploration](https://img.shields.io/badge/Lifecycle-Exploration-339999)
![Delivery](https://img.shields.io/badge/Lifecycle-Delivery-97ca00)
![Dormant](https://img.shields.io/badge/Lifecycle-Dormant-%23ff7f2a)
![Retired](https://img.shields.io/badge/Lifecycle-Retired-d45500)

Adapting from https://www.tidyverse.org/lifecycle/ we could have:
![Maturing](https://img.shields.io/badge/Lifecycle-Maturing-007EC6)
![Experimental](https://img.shields.io/badge/Lifecycle-Experimental-339999)
![Stable](https://img.shields.io/badge/Lifecycle-Stable-97ca00)
![Dormant](https://img.shields.io/badge/Lifecycle-Dormant-%23ff7f2a)
![Retired](https://img.shields.io/badge/Lifecycle-Retired-d45500)

**Comment by AndrewJun97** [comment]
@stephhazlitt @mark-a-wilson Just a quick update:

If a repo does not have a project state badge in the readme, repo-mountie will create an issue with the content in [here]( https://github.com/bcgov/repomountie/blob/d747d432c02c1b91e25ecdb5abc159d943abd05a/templates/state-badges.md).

Please feel free to suggest any changes/additions you’d like to make! :)

**Comment by stephhazlitt** [comment]
@AndrewJun97 🙌 👏

**Comment by mark-a-wilson** [comment]
Thank you for taking this on, @AndrewJun97 !

**Comment by stephhazlitt** [comment]
@AndrewJun97 What do you think of adding the url to the repo page with the descriptions of the states?

e.g.
```[![img](https://img.shields.io/badge/Lifecycle-Experimental-339999)](https://github.com/bcgov/repomountie/blob/8b2ebdc9756819625a56f7a426c29f99b777ab1d/doc/state-badges.md)```

[![img](https://img.shields.io/badge/Lifecycle-Experimental-339999)](https://github.com/bcgov/repomountie/blob/8b2ebdc9756819625a56f7a426c29f99b777ab1d/doc/state-badges.md)

**Comment by stephhazlitt** [comment]
@AndrewJun97 I am wondering about replacing "state" with "lifecycle" in the docs/messaging? I think lifecycle is more meaningful and matches the actual badges? Thoughts @mark-a-wilson?

**Comment by AndrewJun97** [comment]
Thanks for the suggestions @stephhazlitt! I'm happy to make both those changes :)

**Comment by AndrewJun97** [comment]
@stephhazlitt I've updated the docs [here](https://github.com/bcgov/repomountie/blob/66bfbd0bcae12f76b8537066b3a8df24eb370794/templates/lifecycle-badges.md), let me know if you have further suggestions!

**Comment by stephhazlitt** [comment]
Nothing further from me! 🙌

**Comment by stephhazlitt** [comment]
To clarify, this is the eventual `url` for the badge description page, correct? https://github.com/bcgov/repomountie/blob/master/doc/lifecycle-badges.md

**Comment by AndrewJun97** [comment]
> To clarify, this is the eventual `url` for the badge description page, correct? https://github.com/bcgov/repomountie/blob/master/doc/lifecycle-badges.md

Yup, that url was just replaced for demonstrating purposes. The doc and lifecycle badges link to https://github.com/bcgov/repomountie/blob/master/doc/lifecycle-badges.md in the PR. You can find them [here](https://github.com/bcgov/repomountie/blob/e71a5820d59597a26469f8481548ffc6369aa6ac/templates/lifecycle-badges.md) and [here](https://github.com/bcgov/repomountie/blob/e71a5820d59597a26469f8481548ffc6369aa6ac/doc/lifecycle-badges.md)

**Comment by stephhazlitt** [comment]
I'll watch for this being merged. We have an RStudio Addin in the `bcgovr` package that automates inserting badges into .m/.Rmd files, I'll merge the [updated version](https://github.com/bcgov/bcgovr/blob/update-badge-addin/NEWS.md) once this work is live.
