### ISSUE TITLE
Remove Exempt status option

### ISSUE THREAD

**Issue by NickCorcoran** [bcgov/repomountie#65]
Replace "Exempt" with "Not Required - Reviewed with MISO". Description can be the same, with the addition that "the Ministry Information Security Officer has been consulted and agrees that no STRA is required for this repo."

This change is due to terminology used for the Exemption process, which is different from what is taking place here.

**Comment by jleach** [comment]
Looks like we have about 67 repos ATM that have used the `exempt` status. I think we'll need to automate going back and creating a PR with the updates `not-required` status.l

https://github.com/search?q=%22status%3A+exempt%22+in%3Afile+user%3Abcgov+filename%3ACOMPLIANCE.yaml

Query: `"status: exempt" in:file user:bcgov filename:COMPLIANCE.yaml`
