### ISSUE TITLE
Advanced search functionality

### ISSUE THREAD

**Issue by Krocodial** [bcgov/repomountie#90]
Unsure how applicable this is, or if this is something repomountie could/should support, but advanced regex search functionality of 'owned' repos would be useful from a security POV. The use case would be for us to run a regex search on all repos belonging to the teams we support to identify compliance/edge case issues.

Currently this can be done manually by identifying repos belonging to, in our case, the NRM and grepping through the codebase and commit history. Having this functionality be apart of repomountie would allow us to ignore the steps of repo identification and repo cloning

**Comment by jleach** [comment]
I added feature #82 which makes the bot create an issue in every repo asking teams to add a category to their repo that represents the ministry the repo belongs to. For example, if you visit [this](https://github.com/bcgov/repomountie) repo you'll see `citz` in the categories just under the description.

This will help you use GitHub's search to find all your repos. Enter this in the search of GitHub `org:bcgov citz` then on the left you'll see `topics` select it and you'll find `#citz`. This is all the repos (that have been updated) owned by Citizens Services.

**Comment by jleach** [comment]
@Krocodial Also, we are working report. If you contact Nick who is part of our team he can help you get it.

**Comment by Krocodial** [comment]
Oh that's wicked, and then we can rely on github's search functionality. I notice only the initial README, and issues seem to be indexed for search. Attempting to search `return in:file` returns no results. But going into the repo and doing a code search will identify the string in the code file. 

Exact code matches seem to be in beta as well. Is there anyway to search all files in all repos for a string once categorized by topic?

**Comment by jleach** [comment]
@Krocodial This is what one of the issues looks like so you know what topics (short codes) to search by: https://github.com/bcgov/cas-airflow/issues/7

**Comment by Krocodial** [comment]
I'm closing this issue as I think implementing our own code search functionality once sorted by topics is unnecessary and will be better served by github's built-in. Thanks for the info Jason
