### ISSUE TITLE
BCStats not listed in organization list

### ISSUE THREAD

**Issue by MonkmanMH** [bcgov/repomountie#92]
BC Stats has moved between three ministries in the last 3 years, and has a distinct identity separate from the ministry of which it is a part. Please add BC Stats to the org list!

**Comment by jleach** [comment]
@ MonkmanMH Sure. Do you know what the associated short code is?

**Comment by MonkmanMH** [comment]
@jleach Hi, there isn't a separate short code for BC Stats; you are correct that we are currently part of JEDC. I don't expect that we'll ever exist separately from a larger ministry--I like "STAT", let's run with that! Thanks
