### ISSUE TITLE
PSA Description is wrong / Maybe missing PSSG?

### ISSUE THREAD

**Issue by nyatsenk** [bcgov/repomountie#93]
PSA Description is wrong. 
The current description of PSA makes me think that PSSG was meant to be added, however it can go under AG.

Thank you
Nadia Yatsenko

**Comment by jleach** [comment]
@nyatsenk I'll add PSSG and deprecate PSA.

**Comment by ag-pssg-isb-sa** [comment]
Hi @jleach 
Thank you for addressing PSSG. PSA (Public Service Agency) is a valid government entity and you would want to have them on the list too. https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/central-government-agencies/bc-public-service-agency
